### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by 5pelf** [octoshrimpy/ld54-scan-scram#1]
## Week 1: Core Mechanics and Features
- [o] Finalize Game Design Document, set up Godot project
  - [x] doc
  - [x] init godot  
  - [o] single layer worldgen  @jmccardle 
  - [ ] multi-layer worldgen
  - [ ] pathfinding with peeps
    - [-] walking animation
    - [-] climb up/down animation
  - [o] design ship : @octoshrimpy 
  
- [ ] Implement planet scanning mechanic
  - [ ] implement spawn fauna
  - [ ] implement spawn flora
  - [ ] assign points to spawns
  
- [ ] Implement aggressive fauna/flora/natives
  - [ ] flora - does not move
  - [ ] fauna - can run away sometimes
  - [ ] natives - not always agressive, sometimes curious
    - [ ] peep panic animation
    - [ ] natives passive vs angry animation
  
- [ ] Implement researcher death and cloning mechanic
  - [ ] death animation
  - [ ] cloning animation
  
- [ ] Implement basic spaceship upgrades
  - [ ] ship UI
    - [ ] nav UI
    - [ ] clone UI
    - [ ] deploy UI
    
- [ ] Implement research point collection and tracking
  - [ ] internal tracking
  - [ ] peep extra point perks  
  
- [ ] Add basic UI for research points and time limit
  - [ ] fauna bar
  - [ ] flora bar
  - [ ] terrain bar
  - [ ] planet name
  - [ ] found out of total species
  - [ ] current day in research cycle
